### ISSUE TITLE
I've some comments and suggestions

### ISSUE THREAD

**Issue by sujit-baniya** [rdleal/go-async#1]
Thanks for this awesome tool. I was looking for simple workflow tool like this.
I've some questions:

- What will happen to the data, if one of the function throw error or unable to perform it's operation?
- Is there any stat feature for total data in function map being processed for each functions?
- Is individual function async by nature?

I tested this tool with this code and seems the performance is slow when using goroutine
```go
type msg struct {
		Greet, Name string
	}

	fm := async.FuncMap{
		"reader":  strings.NewReader,
		"decoder": async.DependsOn("reader").To(utils.Json.NewDecoder),
		"parser": async.DependsOn("decoder").To(func(d *jsoniter.Decoder) (msg, error) {
			var m msg
			err := d.Decode(&m)
			return m, err
		}),
		"greet": async.DependsOn("parser").To(func(m msg) string {
			return strings.Title(m.Greet)
		}),
		"name": async.DependsOn("parser").To(func(m msg) string {
			return strings.Title(m.Name)
		}),
		"greeter": async.DependsOn("greet", "name").To(func(greet, name string) string {
			return fmt.Sprintf("%s, %s!", greet, name)
		}),
	}
	for i := 0; i < 100; i++ {
		go func(j int) {
			jsonStr := `{"greet": "hello", "name" : "gopher-` + strconv.Itoa(j) + `"}`
			start := time.Now()
			fnc, err := async.Auto(context.Background(), fm, async.WithArgs(jsonStr))
			if err != nil {
				log.Fatal(err)
			}

			for fn := range fnc {
				res, err := fn.Returned()
				if err != nil {
					log.Fatal(err)
				}
				fmt.Println(res[0]) // Hello, Gopher!
			}
			fmt.Println(fmt.Sprintf("%s", time.Since(start)))
		}(i)
	}
```

Result:
```
Hello, Gopher-100!
1.239477ms
Hello, Gopher-100!
28.85µs
Hello, Gopher-100!
1.329145ms
Hello, Gopher-100!
1.231549ms
Hello, Gopher-100!
23.32µs
Hello, Gopher-100!
1.287589ms
Hello, Gopher-100!
1.246905ms
Hello, Gopher-100!
29.173µs
```
Some suggestions:

- Ability to use cache
- Make it fault tolerant: Ability to restart from last function where error occurred or unable to process
- Stats for each functions in a flow

For now I've been using this library to make it happen using Redis and Queue
https://github.com/hibiken/asynq

**Comment by rdleal** [comment]
Hey, @sujit-baniya thank you for taking time for commenting and checking this package against your use case.

> - What will happen to the data, if one of the function throw error or unable to perform it's operation?

The behavior of flow may differ depending on the async function you're using. For exemple, if [Auto](https://pkg.go.dev/github.com/rdleal/go-async/async#Auto) is executing a function that the last or only return value of such function evaluates to a non-nil error, that error will be sent through the `fnc` channel and the functions that depend on the failed one will be not executed, if any.

You may want to check de [docs](https://pkg.go.dev/github.com/rdleal/go-async/async) for finding out how async functions behave in such cases.

> - Is there any stat feature for total data in function map being processed for each functions?

This package is a much lower level workflow tool, which means it doesn't save any state for reporting. It's intent is to encapsulate the work of coordinating goroutines and channels for concurrent execution.

> - Is individual function async by nature?

It depends on which async function is being used. For example:
- [Waterfal](https://pkg.go.dev/github.com/rdleal/go-async/async#Waterfall) will launch a goroutine for executing the whole pipeline, as this is used for sequencial execution, it would be a waste for resource to spawn a goroutine per function.
- [Concurrent](https://pkg.go.dev/github.com/rdleal/go-async/async#Concurrent) will launch a goroutine per function, unless this behavior is overridden by [WithGoroutineNum](https://pkg.go.dev/github.com/rdleal/go-async/async#WithGoroutineNum).
- [Auto](https://pkg.go.dev/github.com/rdleal/go-async/async#Auto) is similar to Concurrent.

As this package makes have use of reflect, the performance may be affected. I'm finding a way of benchmarking it correctly to improve the performance.

Also, thanks for the suggestions. As this package is intended to be simple or simpler than the one you mentioned ([asynq](https://github.com/hibiken/asynq), which seems to offer a higher abstraction than go-async), I think that adding a cache and stats may increase the complexity of the API. Although the retry idea seems a good candidate feature. Something like the [retry of async.js](https://caolan.github.io/async/v3/docs.html#retry), a project that this package is heavily inspired by.

**Comment by sujit-baniya** [comment]
Yes retry is something good feature you could integrate. 
Thanks for the response
